---
- name: Install systemd-unit
  template:
    src: "systemd-loki.j2"
    dest: "/etc/systemd/system/loki.service"
    mode: '0644'
  register: unit_tpl
  notify:
    - reload systemd loki
  when: "__loki_go_os == 'linux'"

- name: Create config directories for loki
  file:
    mode: '0755'
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ loki_config_directory }}"
    - "{{ loki_config_store }}"

- name: Setup configuration
  template:
    src: "loki.yml.j2"
    dest: "/etc/loki/loki.yml"
    mode: '0644'
  register: conf_tpl
  notify:
    - restart systemd loki

- block:
    - name: Download loki release
      get_url:
        url: "{{ __loki_download }}"
        dest: "/tmp/{{ __loki_archive }}"
        checksum: "sha256:{{ __loki_download_github }}/v{{ loki_version }}/SHA256SUMS"
        mode: '0644'
      register: _download_release
      until: _download_release is succeeded
      retries: 5
      delay: 2

    - name: Unpack loki release
      unarchive:
        src: "/tmp/{{ __loki_archive }}"
        dest: "/tmp"
        creates: "/tmp/loki-{{ __loki_go_os }}-{{ __loki_go_arch }}"
        remote_src: true
        mode: '0644'

    - name: Copy loki to /usr/local/bin
      copy:
        src: "/tmp/loki-{{ __loki_go_os }}-{{ __loki_go_arch }}"
        dest: "/usr/local/bin/loki"
        mode: 0755
        owner: root
        group: root
        remote_src: true
      notify: restart systemd loki
  check_mode: false
  when:
    - __loki_version != loki_version

- name: Clean-up
  file:
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - "{{ __loki_archive }}"
    - "loki-{{ __loki_go_os }}-{{ __loki_go_arch }}"
